---
output:
  md_document:
    variant: markdown_github
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-",
  eval = TRUE 
)

mypath <- rprojroot::find_package_root_file
source(mypath("R", "misc.R"))
data_dir <- mypath("data")

library(tidyverse)
library(magrittr)
library(jmotif)
```
# Analyse desassembly and assembly processes in fish communities  

<!-- badges: start -->
<!-- badges: end -->

The goal of this project is to analyze the links between the biomass dynamics
and community structure dynamics.

## Data  

data about communities are located in `data` folder.


```{r load dataset, include = FALSE}
myload(community_metrics, op_analysis, dir = data_dir)
community_metrics %<>% left_join(select(op_analysis, opcod, station, date))
```

```{r}
ts_biomass  <- community_metrics %>%
  select(station, date, biomass) %>%
  mutate(station = as.character(station)) %>%
  group_by(station) %>%
  arrange(date) %>%
  nest()

ts_biomass %<>%
  mutate(
    zts = map(data, function(x) znorm(x$biomass, threshold = 0.01)),
    paa = map(zts, ~paa(., 3)),
    sax = map_chr(paa, ~series_to_string(., 3))
  )
```

```{r}
pattern_dist <- ts_biomass %>%
  group_by(sax) %>%
  summarise(count = n()) %>%
  arrange(desc(count))
ggplot(ts_biomass, aes(x = sax)) +
  geom_histogram(stat = "count")

filter(pattern_dist, count > 10)
```

```{r}
test <- ts_biomass %>%
  filter(sax %in% c("cba", "bbb", "cab", "abc", "acb", "bca", "bac", "cbb")) %>%
  group_by(sax) %>%
  sample_n(10) %>%
  mutate(
    paa2 = map2(data, zts, function (x, zts) {
      cbind(x[,1], zts)
  }),
    id_sta = as.character(seq(1,n()))

  ) %>%
  unnest(paa2)

ggplot(test, aes(x = date, y = zts)) +
  geom_line(aes(color = id_sta)) +
  facet_wrap(~ sax)

```

