#' Add number of year since start
#'
#' @param .data a df e.g. generated by get_full_data()
add_nb_year_station <- function (.data = NULL) {
  
  output <- .data %>%
    group_by(station) %>%
    mutate(nb_year = year - min(year)) %>%
    ungroup()
  return(output)
}


#' Add biomass value, relative to the first year 
#'
#' @param .data a df e.g. generated by get_full_data()
add_relative_biomass_to_start <- function (.data = NULL) {
  
  output <- .data %>%
    dplyr::group_by(station) %>%
    dplyr::arrange(nb_year) %>%
    dplyr::mutate(rel_bm = (biomass - first(biomass)) / first(biomass)) %>%
    dplyr::ungroup()
  return(output)
}

#' Compute derivate variables
#'
#' @inheritParams add_relative_biomass_to_start 
add_to_full_data <- function (.data = NULL) {

  output <- add_nb_year_station(.data)  
  output <- add_relative_biomass_to_start(output) 

  return(output)
}
