---
title: "Wordstack and outline of the manuscript"
author: "Alain Danet"
self_contained: yes
date: "`r Sys.Date()`"
tables: yes
output:
  prettydoc::html_pretty:
    theme: cayman
    highlight: github
    math: katex
---

# Main messages

- Different assembly processes between biomass and richness
  - 
- Space for time works well for biomass but less for species richness
  - Connectance and average trophic level

# Wordstack

- Foodwebs
- interactions
- perturbation/perturbation sequences
- network structure
- temporal dynamics
- BEF
- space for time
- extinction sequences

- omnivory
- equilibrium / dynamics

# Outline

### Introduction


1. Global trends of biodiversity
   1. Global declines and threats 
   2. Reported richness and biomass trends
   3. Continue to explore trends in community structure and its consequences

2. Ecological communities are ecological networks
   1. Species interactions matter for ecosystem functioning
   2.  
3. Trends in richness and biomass should result in alteration of ecological
   networks 
   1. Spatial prediction
   2. But space-for-time...

4. Limitations before this study
   1. Low availability of long temporal series 
   1. No reconstruction method
   1.

5. Study objectives


3. Colonisation / Extinction sequences in natural settings
    1. Space for time substitution
    2. Communities are not affected randomly as environment species niche
    3. sequence: is losing something = adding something ?
    4. assembly / disassembly processes 

2. Community structure dimension are linked 
    1. Biomass and species richness 
	1. experiment: richness and productivity richness and stability
	2. Empirical:
    2. Foodweb/Network structure and biomass/richness 
	1. connectance richness
	2. persistance / connectance

 
4. Research questions 
    1. Link between the temporal dynamics of different aspects of community structure ?
	1. Is BEF valid? 
	2. is space for time substitution?
    2. effect of assembly/disassembly

5. blabla Foodweb/fish/super huge top dataset


## Material and methods

1. Data selection
2. Community biomass and richness 
3. Network reconstruction
4. Temporal trends 
5. Statistical analysis

## Results

1. No effects of community assembly/disassembly

2. Community structure and biomass
    1. positive links everywhere except piel ind (neutral) and piel biomass
       (negative)
    2. No effect of differences between gain and losses

3. Community structure and species richness
   1. Positive links everywhere except connectance

## Discussion

1. Temporal trends valid theory: BEF 
    1. Total Biomass and species richness 
	- plant: [@tilman_productivity_1996; @grace_integrative_2016;
	  @hector_plant_1999; @tilman_biodiversity_2014;
	  @grace_integrative_2016]
	- stream feeders: [@cardinale_species_2002]
	- aquatic bacterial consumers [@pennekamp_biodiversity_2018]
    2. Connectance and species richness: [@dunne_network_2006]
    3. Tlvl and species richness: []
    4. Evenness increases with species richness:
       - It is expected when adding species lead to a transfert of indiv [@jost_relation_2010]
       - Losses of species richness leads to more dominance of few species
       - Negative selection effect? See [@maureaud_biodiversity_2019]
       - Evenness is often positively linked to species richness
	 [@soininen_relationship_2012]
       
    
2. Biomass temporal dynamics is linked to the top trophic level
   [@maureaud_biodiversity_2019] found neg biomass-eveness (indiv).
    1. Top predators represent both few individuals and most of the biomass 
    2. Predators are key to the network structure

3. Biomass and richness variation are not the same process 
    1. Linked to few big individuals for biomass 
    2. Linked to dominance for richness

4. Biomass and richness gains and losses are symmetric processes in terms of
   community structure
    1. Because big individuals are drivers
    2. We could have imagine other ways, that losses and gain of biomass/species
       are overall due to little individuals. Is it a statistical or an
       ecological effect? because big individuals are less numerous? (can be
       check with nind in covariable?)

5. Space for time substitution does not always hold

6. Are community dynamics fluctuate around equilibrium point
